"""recherches enregistrees

Revision ID: 09ce4a13109c
Revises: 810b07396132
Create Date: 2026-08-29 18:37:46.887835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # types AutoString generes par SQLModel


# revision identifiers, used by Alembic.
revision: str = '09ce4a13109c'
down_revision: Union[str, Sequence[str], None] = '810b07396132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recherche',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mots_cles', sa.JSON(), nullable=False),
    sa.Column('pays', sa.JSON(), nullable=False),
    sa.Column('contrats', sa.JSON(), nullable=False),
    sa.Column('departement', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('publiee_depuis_jours', sa.Integer(), nullable=True),
    sa.Column('max_offres', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recherche', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recherche_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_recherche_nom'), ['nom'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recherche', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recherche_nom'))
        batch_op.drop_index(batch_op.f('ix_recherche_active'))

    op.drop_table('recherche')
    # ### end Alembic commands ###
