"""date de derniere vue des offres

Revision ID: 23f2918f21d1
Revises: 09ce4a13109c
Create Date: 2026-08-29 20:04:42.213993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # types AutoString generes par SQLModel


# revision identifiers, used by Alembic.
revision: str = '23f2918f21d1'
down_revision: Union[str, Sequence[str], None] = '09ce4a13109c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        # SQLite refuse une colonne NOT NULL sans valeur pour les lignes existantes.
        # Les offres deja en base sont reputees vues au moment de la migration.
        batch_op.add_column(sa.Column('derniere_vue_le', sa.DateTime(), nullable=False,
                                      server_default=sa.text('CURRENT_TIMESTAMP')))
        batch_op.create_index(batch_op.f('ix_offer_derniere_vue_le'), ['derniere_vue_le'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offer_derniere_vue_le'))
        batch_op.drop_column('derniere_vue_le')

    # ### end Alembic commands ###
