"""annees d experience du profil

Revision ID: 4c567d4a7400
Revises: 87dad6698c85
Create Date: 2026-08-30 20:09:54.456068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # types AutoString generes par SQLModel


# revision identifiers, used by Alembic.
revision: str = '4c567d4a7400'
down_revision: Union[str, Sequence[str], None] = '87dad6698c85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        # server_default indispensable : la table porte deja une ligne, et SQLite
        # refuse une colonne NOT NULL sans valeur par defaut.
        batch_op.add_column(sa.Column('annees_experience', sa.Integer(),
                                      nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('annees_experience')

    # ### end Alembic commands ###
