"""schema initial

Revision ID: 810b07396132
Revises: 
Create Date: 2026-08-28 20:37:08.022306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '810b07396132'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_cache',
    sa.Column('cle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hash_source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modele', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('cle')
    )
    with op.batch_alter_table('llm_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_cache_hash_source'), ['hash_source'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_cache_type'), ['type'], unique=False)

    op.create_table('offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('titre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entreprise', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lieu', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pays', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type_contrat', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_publication', sa.DateTime(), nullable=True),
    sa.Column('date_recuperation', sa.DateTime(), nullable=False),
    sa.Column('description_brute', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('score_detail', sa.JSON(), nullable=False),
    sa.Column('score_explication', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scored_at', sa.DateTime(), nullable=True),
    sa.Column('poids_version', sa.Integer(), nullable=True),
    sa.Column('extraction', sa.JSON(), nullable=False),
    sa.Column('extraction_modele', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extraction_at', sa.DateTime(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('vue', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_offer_source')
    )
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.create_index('ix_offer_date_publication', ['date_publication'], unique=False)
        batch_op.create_index('ix_offer_hash', ['hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_offer_pays'), ['pays'], unique=False)
        batch_op.create_index('ix_offer_score', ['score'], unique=False)
        batch_op.create_index(batch_op.f('ix_offer_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_offer_type_contrat'), ['type_contrat'], unique=False)
        batch_op.create_index(batch_op.f('ix_offer_vue'), ['vue'], unique=False)

    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prenom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telephone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ville', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pays', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('linkedin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('titre_vise', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resume', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secteurs', sa.JSON(), nullable=False),
    sa.Column('langues', sa.JSON(), nullable=False),
    sa.Column('pays_acceptes', sa.JSON(), nullable=False),
    sa.Column('contrats_acceptes', sa.JSON(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('experiences', sa.JSON(), nullable=False),
    sa.Column('formations', sa.JSON(), nullable=False),
    sa.Column('cv_source_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cv_importe_le', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('requete', sa.JSON(), nullable=False),
    sa.Column('nb_recuperees', sa.Integer(), nullable=False),
    sa.Column('nb_nouvelles', sa.Integer(), nullable=False),
    sa.Column('nb_doublons', sa.Integer(), nullable=False),
    sa.Column('nb_rejetees', sa.Integer(), nullable=False),
    sa.Column('nb_appels_llm', sa.Integer(), nullable=False),
    sa.Column('erreurs', sa.JSON(), nullable=False),
    sa.Column('statut', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('declenche_par', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_run_started_at'), ['started_at'], unique=False)

    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('date_candidature', sa.DateTime(), nullable=False),
    sa.Column('statut', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dossier_local', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_offer_id'), ['offer_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_application_statut'), ['statut'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_statut'))
        batch_op.drop_index(batch_op.f('ix_application_offer_id'))

    op.drop_table('application')
    with op.batch_alter_table('scan_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_run_started_at'))

    op.drop_table('scan_run')
    op.drop_table('profile')
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offer_vue'))
        batch_op.drop_index(batch_op.f('ix_offer_type_contrat'))
        batch_op.drop_index(batch_op.f('ix_offer_source'))
        batch_op.drop_index('ix_offer_score')
        batch_op.drop_index(batch_op.f('ix_offer_pays'))
        batch_op.drop_index('ix_offer_hash')
        batch_op.drop_index('ix_offer_date_publication')

    op.drop_table('offer')
    with op.batch_alter_table('llm_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_cache_type'))
        batch_op.drop_index(batch_op.f('ix_llm_cache_hash_source'))

    op.drop_table('llm_cache')
    # ### end Alembic commands ###
