"""situation actuelle et disponibilite du profil

Revision ID: 87dad6698c85
Revises: 23f2918f21d1
Create Date: 2026-08-30 05:09:33.224672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # types AutoString generes par SQLModel


# revision identifiers, used by Alembic.
revision: str = '87dad6698c85'
down_revision: Union[str, Sequence[str], None] = '23f2918f21d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # `server_default` est indispensable : la table porte deja une ligne, et
    # SQLite refuse d'ajouter une colonne NOT NULL sans valeur par defaut.
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('situation_actuelle', sqlmodel.sql.sqltypes.AutoString(),
                                      nullable=False, server_default=''))
        batch_op.add_column(sa.Column('disponibilite', sqlmodel.sql.sqltypes.AutoString(),
                                      nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('disponibilite')
        batch_op.drop_column('situation_actuelle')

    # ### end Alembic commands ###
