"""accord grammatical du profil

Revision ID: d96aa6480cfe
Revises: 4c567d4a7400
Create Date: 2026-09-24 04:37:55.904358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # types AutoString generes par SQLModel


# revision identifiers, used by Alembic.
revision: str = 'd96aa6480cfe'
down_revision: Union[str, Sequence[str], None] = '4c567d4a7400'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accord', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('accord')

    # ### end Alembic commands ###
